%YAML:1.0

#common parameters
imu: 1         
num_of_cam: 2  

imu_topic: "/imu/frd"
image0_topic: "/stereo/left/image_raw_sync"
image1_topic: "/stereo/right/image_raw_sync"
output_path: "~/output/"

cam0_calib: "DJ_left.yaml"
cam1_calib: "DJ_right.yaml"
image_width: 480
image_height: 480

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.99955321, -0.02478411, 0.01670712, 0.00162554,
         -0.01796262, -0.05133132, 0.99852013, 0.00032589,
         -0.02388983, -0.9983741, -0.05175357, 0.00008179,
         0.0, 0.0, 0.0, 1.0]
          
body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.99932924, -0.02631758, 0.02546495, 0.06792107,
         -0.02688728, -0.05518451, 0.99811409, -0.00049944,
         -0.02486268, -0.99812928, -0.05585511, -0.00142066,
         0.0, 0.0, 0.0, 1.0]
          
#Multiple thread support
multiple_thread: 1

#feature traker parameters
max_cnt: 150
min_dist: 30
freq: 80
F_threshold: 1.0
show_track: 1
flow_back: 1

#optimization parameters
max_solver_time: 0.06
max_num_iterations: 10
keyframe_parallax: 5.0

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.002          # accelerometer measurement noise standard deviation. 
gyr_n: 0.0006         # gyroscope measurement noise standard deviation.     
acc_w: 0.00002       # accelerometer bias random work noise standard deviation.  
gyr_w: 0.000003       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/sbim/vins_ws/data/path/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
